### ISSUE TITLE
Is there a way to @import a webfont for specific domain only?

### ISSUE THREAD

**Issue by rulatir** [JasonBarnabe/stylish#223]
@import isn't accepted inside the @-moz-document declaration due to the DREADED restriction requiring that @import rules precede all other rules.

How can I use Google fonts in my stylesheets while avoiding the situation where every webfont CSS I @import outside of @-moz-document in any of my user stylesheets gets loaded on every page I visit?

I can probably just download the webfont stylesheets and paste their contents inside the @-moz-document declaration, adjusting URLs where necessary, but that's a lot of manual work.

Can I somehow circumvent the @import limitation in a workable way? Please update the FAQ with the answer, even if it will be "no can do".

**Comment by seboss666** [comment]
Even without the @import mechanism, it's the whole webfont definition I can't get to work. First time I thought it was the url (I was trying to link a raw file on github), but after using a file on a standard http server, without SSL and all, no way.

Is it just possible to define a distant webfont in a user style ?

**Comment by JasonBarnabe** [comment]
Can you post your CSS?

**Comment by JasonBarnabe** [comment]
Without an example, there's not much I can do.

**Comment by lolmaus** [comment]
This code works perfectly in Stylish for Chrome:

```css
@import url('https://fonts.googleapis.com/css?family=Lato:400,400i,900,900i');

html,button,input,select,textarea{
    font-family: Lato, sans-serif;
}
```

I want to share it on userstyles.org. I click `Export to Mozilla format`, and the resulting CSS is not accepted by the website:

```css
@-moz-document domain("www.flowdock.com") {
	@import url('https://fonts.googleapis.com/css?family=Lato:400,400i,900,900i');

	html,button,input,select,textarea{
	    font-family: Lato, sans-serif;
	}
}
```

Please reopen!
