### ISSUE TITLE
Can I do replace specific font with another font?

### ISSUE THREAD

**Issue by nvcken** [JasonBarnabe/stylish#283]

**Comment by easyaspi314** [comment]
It is really simple. Lengthy, but simple. Let's say you want to replace Arial with Fira Sans. First, you install the font locally. You can use a CDN or even embed fonts in a URI (don't do it), but it is slow as Helvetica. (Font jokes)

```css
/* AGENT_SHEET */
@font-face { font-family: 'Arial'; font-weight: normal; src: local('Fira Sans'); }
@font-face { font-family: 'Arial'; font-weight: bold; src: local('Fira Sans Bold'); }
```

You can't replace `serif`, `sans-serif`, or `monospace`, but you can use Firefox's preferences > content (iirc) to set those. You can even change the UI font by replacing `system` and `-apple-system` (these must be w/o quotes)
